Repository prettier/plugin-pug, pull requests merged in 2020-09, with the labels that each got.

#108 Fix pug in brackets turned into multi line
  tests/issues/issue-107/formatted.pug
  tests/issues/issue-107/issue-107.test.ts
  tests/issues/issue-107/unformatted.pug
Labels: type: bug

#111 Fix indentation of objects in multiline class attributes
  src/printer.ts
  tests/issues/issue-110/formatted.pug
  tests/issues/issue-110/issue-110.test.ts
  tests/issues/issue-110/unformatted.pug
Labels: type: bug

#106 Add pug aliased options
  CHANGELOG.md
  README.md
  src/index.ts
  src/options/attribute-separator.ts
  src/options/closing-bracket-position.ts
  src/options/comment-preserve-spaces.ts
  src/options/common.ts
  src/options/converge.ts
  src/options/index.ts
  src/printer.ts
  tests/issues/issue-105/formatted.vue
  tests/issues/issue-105/issue-105.test.ts
  tests/issues/issue-105/unformatted.vue
  tests/options/attributeSeparator/always/always.test.ts
  tests/options/attributeSeparator/as-needed/as-needed.test.ts
  tests/options/singleQuote/single-quote.test.ts
Labels: framework: Vue, type: feature request

#117 Pass on more prettier code-interpolation options
  src/options/common.ts
  src/options/converge.ts
  src/options/index.ts
  src/printer.ts
Labels: type: enhancement

#116 Allow "none" as an option for attributeSeparator
  README.md
  src/options/attribute-separator.ts
  src/printer.ts
  tests/options/attributeSeparator/none/angular-formatted.pug
  tests/options/attributeSeparator/none/angular-unformatted.pug
  tests/options/attributeSeparator/none/formatted.pug
  tests/options/attributeSeparator/none/none.test.ts
  tests/options/attributeSeparator/none/unformatted.pug
Labels: type: enhancement

#23 Support sorting of attributes
  src/options/attribute-sorting/index.ts
  src/options/attribute-sorting/utils.ts
  src/options/converge.ts
  src/options/index.ts
  src/printer.ts
  tests/options/sortAttributes/formatted.pug
  tests/options/sortAttributes/sort-attributes.test.ts
  tests/options/sortAttributes/unformatted.pug
Labels: type: feature request
