Repository prettier/plugin-pug, pull requests merged in 2020-10, with the labels that each got.

#127 Implement pugWrapAttributesPattern option
  README.md
  src/options/converge.ts
  src/options/index.ts
  src/options/wrap-attributes.ts
  src/printer.ts
  tests/options/pugWrapAttributesPattern/formatted.pug
  tests/options/pugWrapAttributesPattern/unformatted.pug
  tests/options/pugWrapAttributesPattern/wrap-attributes-pattern.test.ts
Labels: type: feature request

#121 Fix counting of current line-length
  README.md
  src/printer.ts
  tests/options/attributeSeparator/always/always.test.ts
  tests/options/attributeSeparator/always/formatted.pug
  tests/options/attributeSeparator/always/unformatted.pug
  tests/options/attributeSeparator/as-needed/as-needed.test.ts
  tests/options/attributeSeparator/as-needed/formatted.pug
  tests/options/attributeSeparator/as-needed/unformatted.pug
  tests/options/attributeSeparator/none/formatted.pug
  tests/options/attributeSeparator/none/none.test.ts
  tests/options/attributeSeparator/none/unformatted.pug
Labels: type: enhancement

#131 Fix handling of combined literal attributes
  src/printer.ts
  tests/literals/id-class-literals/formatted.pug
  tests/literals/id-class-literals/id-class-literals.test.ts
  tests/literals/id-class-literals/unformatted.pug
  tests/options/pugWrapAttributesThreshold/0/formatted.pug
  tests/options/pugWrapAttributesThreshold/0/unformatted.pug
  tests/options/pugWrapAttributesThreshold/1/formatted.pug
  tests/options/pugWrapAttributesThreshold/1/unformatted.pug
  tests/options/pugWrapAttributesThreshold/2/formatted.pug
  tests/options/pugWrapAttributesThreshold/2/unformatted.pug
  tests/options/pugWrapAttributesThreshold/default/formatted.pug
  tests/options/pugWrapAttributesThreshold/default/unformatted.pug
Labels: type: bug

#125 Support prettier-ignore comments inside pug templates
  .editorconfig
  README.md
  src/index.ts
  src/printer.ts
  tests/prettier-ignore/formatted.pug
  tests/prettier-ignore/prettier-ignore.test.ts
  tests/prettier-ignore/unformatted.pug
Labels: type: feature request

#134 Improve conversion of tags to literals
  src/printer.ts
  tests/literals/matching-content/formatted.pug
  tests/literals/matching-content/matching-content.test.ts
  tests/literals/matching-content/unformatted.pug
Labels: type: enhancement

#139 Fix issues with plain-text and nesting (#138)
  src/printer.ts
  tests/plain-text/formatted.pug
  tests/plain-text/unformatted.pug
Labels: type: bug

#141 Support indentation for SFC
  README.md
  src/options/converge.ts
  src/options/index.ts
  src/options/pug-single-file-component-indentation.ts
  src/printer.ts
  tests/options/pugTemplateTagIndentation/indented.vue
  tests/options/pugTemplateTagIndentation/not-indented.md
  tests/options/pugTemplateTagIndentation/not-indented.vue
  tests/options/pugTemplateTagIndentation/pug-template-tag-indentation.test.ts
Labels: framework: Svelte, framework: Vue, type: feature request

#142 Add option for Empty Attributes
  README.md
  src/options/converge.ts
  src/options/empty-attributes/index.ts
  src/options/empty-attributes/utils.ts
  src/options/index.ts
  src/printer.ts
  tests/common.ts
  tests/options/emptyAttributes/empty-attributes.test.ts
  tests/options/emptyAttributes/formatted.pug
  tests/options/emptyAttributes/unformatted.pug
  tests/options/sortAttributes/sort-attributes.test.ts
Labels: type: feature request

#146 Fix handling of initial indentation for pugSingleFileComponentIndentation
  src/index.ts
  src/printer.ts
  tests/issues/issue-145/extends-formatted.vue
  tests/issues/issue-145/extends-unformatted.vue
  tests/issues/issue-145/formatted.pug
  tests/issues/issue-145/formatted.vue
  tests/issues/issue-145/issue-145.test.ts
  tests/issues/issue-145/unformatted.pug
  tests/issues/issue-145/unformatted.vue
  tests/options/pugTemplateTagIndentation/pug-template-tag-indentation.test.ts
  tests/options/pugTemplateTagIndentation/two-div-indented-flat.vue
  tests/options/pugTemplateTagIndentation/two-div-indented-tree.vue
  tests/options/pugTemplateTagIndentation/two-div-not-indented-flat.vue
  tests/options/pugTemplateTagIndentation/two-div-not-indented-tree.vue
Labels: framework: Vue, type: bug

#151 Add pug to vscodeLanguageIds
  src/index.ts
Labels: type: enhancement

#152 Fix bracket interpolation in combination with pugSingleFileComponentIndentation
  src/printer.ts
  tests/issues/issue-148/formatted.vue
  tests/issues/issue-148/issue-148.test.ts
  tests/issues/issue-148/unformatted.vue
Labels: framework: Vue, type: bug
