Repository prettier/plugin-pug, pull requests merged in 2020-05, with the labels that each got.

#83 Feature: closing bracket position option added
  README.md
  src/index.ts
  src/options/index.ts
  src/printer.ts
  test/options/closingBracketPosition/last-line/formatted.pug
  test/options/closingBracketPosition/last-line/last-line.test.ts
  test/options/closingBracketPosition/last-line/unformatted.pug
  test/options/closingBracketPosition/new-line/formatted.pug
  test/options/closingBracketPosition/new-line/new-line.test.ts
  test/options/closingBracketPosition/new-line/unformatted.pug
Labels: type: feature request

#84 Bugfix: nested closed brackets was causing a dash bug
  src/printer.ts
  test/options/closingBracketPosition/last-line/formatted.pug
  test/options/closingBracketPosition/last-line/unformatted.pug
Labels: type: bug

#86 Fix readme
  README.md
Labels: type: documentation

#87 Fix semi in code interpolation
  src/printer.ts
  test/issues/issue-85/formatted.pug
  test/issues/issue-85/issue-85.test.ts
  test/issues/issue-85/unformatted.pug
Labels: type: bug

#93 Fix indention in multi-line blank lines
  src/printer.ts
  test/issues/issue-89/formatted.pug
  test/issues/issue-89/issue-89.test.ts
  test/issues/issue-89/unformatted.pug
Labels: type: enhancement

#94 Do not reformat interpolation attribute values
  src/printer.ts
  src/utils/common.ts
  test/issues/issue-80/formatted.pug
  test/issues/issue-80/issue-80.test.ts
  test/issues/issue-80/unformatted.pug
Labels: type: enhancement
