Repository prettier/plugin-pug, pull requests merged in 2020-11, with the labels that each got.

#154 Do not wrap attributes in enclosed code interpolation
  src/printer.ts
  tests/issues/issue-149/formatted.pug
  tests/issues/issue-149/issue-149.test.ts
  tests/issues/issue-149/unformatted.pug
Labels: type: bug

#155 Print warning for parsed object shorthand notation
  src/printer.ts
  tests/issues/issue-147/formatted.pug
  tests/issues/issue-147/issue-147.test.ts
  tests/issues/issue-147/unformatted.pug
Labels: framework: Vue, type: enhancement

#132 Handle for...of in vue v-for
  src/printer.ts
  src/utils/vue.ts
  tests/issues/issue-129/formatted.pug
  tests/issues/issue-129/issue-129.test.ts
  tests/issues/issue-129/unformatted.pug
Labels: framework: Vue, type: bug

#159 Format inline scripts and styles
  .gitignore
  src/printer.ts
  src/utils/common.ts
  tests/issues/issue-158/formatted.pug
  tests/issues/issue-158/issue-158.test.ts
  tests/issues/issue-158/unformatted.pug
  tests/pug-tests/pug.test.ts
  tests/pug-tests/script.whitespace.formatted.pug
  tests/pug-tests/script.whitespace.pug
  tests/pug-tests/styles.formatted.pug
  tests/pug-tests/styles.pug
Labels: type: enhancement

#163 Format value of style attribute in tags
  src/printer.ts
  src/utils/common.ts
  tests/issues/issue-162/formatted.pug
  tests/issues/issue-162/issue-162.test.ts
  tests/issues/issue-162/unformatted.pug
  tests/pug-tests/styles.formatted.pug
Labels: type: enhancement

#153 Add option for use class and id literals
  README.md
  src/options/converge.ts
  src/options/index.ts
  src/options/pug-class-notation.ts
  src/options/pug-id-notation.ts
  src/printer.ts
  tests/options/pugClassNotation/formatted-literal.pug
  tests/options/pugClassNotation/pug-class-notation.test.ts
  tests/options/pugClassNotation/unformatted.pug
  tests/options/pugIdNotation/formatted-attribute.pug
  tests/options/pugIdNotation/formatted-literal.pug
  tests/options/pugIdNotation/pug-id-notation.test.ts
Labels: help wanted, type: feature request
