Repository prettier/plugin-pug, pull requests merged in 2021-07, with the labels that each got.

#242 feat: explicit div pug option
  docs/guide/pug-specific-options.md
  src/options/converge.ts
  src/options/index.ts
  src/options/pug-explicit-div.ts
  src/printer.ts
  tests/options/pugExplicitDiv/formatted-explicit-div.pug
  tests/options/pugExplicitDiv/formatted-implicit-div.pug
  tests/options/pugExplicitDiv/pug-explicit-div.test.ts
  tests/options/pugExplicitDiv/unformatted.pug
Labels: type: feature request

#239 Add case to handle single line interpolated attributes
  src/printer.ts
  src/utils/common.ts
  tests/issues/issue-238/formatted.pug
  tests/issues/issue-238/issue-238.test.ts
  tests/issues/issue-238/unformatted.pug
Labels: type: bug

#249 Handle non-JS script content
  .eslintrc.js
  .vscode/settings.json
  src/printer.ts
  src/utils/common.ts
  src/utils/script-mime-types.ts
  tests/syntax-errors/scripts-with-non-js-contents.pug
  tests/syntax-errors/syntax-errors.test.ts
Labels: type: bug

#248 Handle non-JS script content improvements
  src/printer.ts
  src/utils/common.ts
  src/utils/script-mime-types.ts
  tests/issues/issue-244/formatted.pug
  tests/issues/issue-244/issue-244.test.ts
  tests/issues/issue-244/unformatted.pug
Labels: type: bug

#252 Fix corrupt attribute values on dynamically bound Vue props without quotes
  src/printer.ts
  src/utils/common.ts
  tests/issues/issue-250/formatted.pug
  tests/issues/issue-250/issue-250.test.ts
  tests/issues/issue-250/unformatted.pug
  tests/issues/issue-61/formatted.pug
  tests/issues/issue-61/unformatted.pug
  tests/issues/issue-80/formatted.pug
  tests/issues/issue-80/unformatted.pug
Labels: framework: Vue, type: bug

#256 Prevent wrong quotation
  src/printer.ts
  tests/issues/issue-255/formatted.pug
  tests/issues/issue-255/issue-255.test.ts
  tests/issues/issue-255/unformatted.pug
Labels: type: bug
