Repository prettier/plugin-pug, pull requests merged in 2021-08, with the labels that each got.

#266 Preserve backticks for class and id attributes
  .vscode/settings.json
  src/printer.ts
  tests/issues/issue-261/formatted.pug
  tests/issues/issue-261/issue-261.test.ts
  tests/issues/issue-261/unformatted.pug
Labels: type: bug

#267 Apply useTabs also for code interpolations
  src/printer.ts
  tests/issues/issue-262/formatted.pug
  tests/issues/issue-262/issue-262.test.ts
  tests/issues/issue-262/unformatted.pug
Labels: type: bug

#271 Add `.vscode/launch.json` for debugging
  .vscode/launch.json
  jest.config.js
Labels: type: enhancement

#279 Fix trailing indentations after pipeless text
  src/printer.ts
  tests/issues/issue-278/formatted.pug
  tests/issues/issue-278/issue-278.test.ts
  tests/issues/issue-278/unformatted.pug
Labels: type: bug

#283 Fix indentation of templates starting with class or ID when using pugSingleFileComponentIndentation
  src/printer.ts
  tests/issues/issue-282/class-indented.vue
  tests/issues/issue-282/class-not-indented.vue
  tests/issues/issue-282/id-indented.vue
  tests/issues/issue-282/id-not-indented.vue
  tests/issues/issue-282/issue-282.test.ts
Labels: type: bug, framework: Vue
