Repository prettier/plugin-pug, pull requests merged in 2021-04, with the labels that each got.

#186 Add framework option
  README.md
  src/options/converge.ts
  src/options/index.ts
  src/options/pug-framework.ts
  src/options/pug-id-notation.ts
  src/printer.ts
  src/utils/common.ts
  tests/frameworks/detection.test.ts
  tests/frameworks/vue/v-bind/v-bind.test.ts
  tests/frameworks/vue/v-model/v-model.test.ts
  tests/frameworks/vue/v-on/v-on.test.ts
  tests/frameworks/vue/v-slot/v-slot.test.ts
  tests/interpolations/formatted_angular.pug
  tests/interpolations/formatted_none.pug
  tests/interpolations/formatted_vue.pug
  tests/interpolations/interpolations.test.ts
  tests/interpolations/unformatted_angular.pug
  tests/interpolations/unformatted_none.pug
  tests/interpolations/unformatted_vue.pug
  tests/issues/issue-70/issue-70.test.ts
  tests/issues/issue-9/issue-9.test.ts
Labels: framework: Angular, framework: Svelte, framework: Vue, type: feature request

#191 Initiate VuePress documentation
  .eslintrc.js
  .github/workflows/docs.yml
  .gitignore
  .prettierignore
  .vscode/settings.json
  README.md
  deploy-docs.sh
  docs/.vuepress/config.js
  docs/.vuepress/public/icon.png
  docs/.vuepress/styles/index.styl
  docs/guide/README.md
  docs/guide/pug-specific-options.md
  docs/guide/standard-prettier-overrides.md
  docs/index.md
  package.json
  src/utils/common.ts
  yarn.lock
Labels: type: documentation

#202 Rename pugFramework default to auto
  docs/guide/pug-specific-options.md
  src/options/pug-framework.ts
  src/printer.ts
  src/utils/common.ts
  tests/frameworks/detection.test.ts
Labels: type: enhancement

#203 Add pugClassNotation 'attribute' option
  docs/guide/pug-specific-options.md
  src/options/pug-class-notation.ts
  src/printer.ts
  tests/options/pugClassNotation/formatted-attribute.pug
  tests/options/pugClassNotation/formatted-literal.pug
  tests/options/pugClassNotation/pug-class-notation.test.ts
  tests/options/pugClassNotation/unformatted.pug
Labels: type: feature request
