Repository prettier/plugin-pug, pull requests merged in 2024-09, with the labels that each got.

#502 Add option to set indent depth of closing brackets
  docs/guide/pug-specific-options.md
  src/options/converge.ts
  src/options/index.ts
  src/options/pug-closing-bracket-indent-depth.ts
  src/options/types.ts
  src/printer.ts
  tests/options/pugClosingBracketIndentDepth/depth-0.pug
  tests/options/pugClosingBracketIndentDepth/depth-1.pug
  tests/options/pugClosingBracketIndentDepth/pug-closing-bracket-indent-depth.test.ts
  tests/options/pugClosingBracketIndentDepth/unformatted.pug
Labels: type: feature request

#503 Fix class attributes not counting towards attribute wrapping
  src/printer.ts
  tests/options/pugWrapAttributesThreshold/withAsIsClassNotation/formatted.pug
  tests/options/pugWrapAttributesThreshold/withAsIsClassNotation/unformatted.pug
  tests/options/pugWrapAttributesThreshold/withAsIsClassNotation/with-as-is-class-notation.test.ts
  tests/options/pugWrapAttributesThreshold/withAsIsIdNotation/formatted.pug
  tests/options/pugWrapAttributesThreshold/withAsIsIdNotation/unformatted.pug
  tests/options/pugWrapAttributesThreshold/withAsIsIdNotation/with-as-is-id-notation.test.ts
  tests/options/pugWrapAttributesThreshold/withAttributeClassNotation/formatted.pug
  tests/options/pugWrapAttributesThreshold/withAttributeClassNotation/unformatted.pug
  tests/options/pugWrapAttributesThreshold/withAttributeClassNotation/with-attribute-class-notation.test.ts
Labels: type: bug

#504 Update devDependencies
  package.json
  pnpm-lock.yaml
  src/printer.ts
Labels: dependencies

#505 Pin devDependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies
